before:
  hooks:
    - go get -u -d ./...
builds:
  -
    main: ./cmd/amass/main.go
    binary: amass
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - 386
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386

  -
    main: ./cmd/amass.netdomains/main.go
    binary: amass.netdomains
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - 386
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386

  -
    main: ./cmd/amass.viz/main.go
    binary: amass.viz
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - 386
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386

  -
    main: ./cmd/amass.db/main.go
    binary: amass.db
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - 386
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386

  -
    main: ./cmd/amass.tracker/main.go
    binary: amass.tracker
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - 386
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386

archive:
  name_template: "amass_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  replacements:
    darwin: macos
    386: i386
  wrap_in_directory: true
  format: zip
  files:
    - LICENSE
    - README.md
    - wordlists/*

checksum:
  name_template: "amass_checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^doc:'
    - '^test:'

brew:
  name: amass
  github:
    owner: caffix
    name: homebrew-amass
  url_template: "http://github.com/OWASP/Amass/releases/download/{{ .Version }}/amass_{{ .Version }}_macos_amd64.zip"
  download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy
  commit_author:
    name: caffix
    email: caffix@users.noreply.github.com
  folder: Formula
  homepage: "https://www.owasp.org/index.php/OWASP_Amass_Project"
  description: "In-depth DNS Enumeration and Network Mapping"
  install: |
    bin.install "amass"
    bin.install "amass.netdomains"
    bin.install "amass.viz"
    bin.install "amass.db"
    bin.install "amass.tracker"

