[[constraint]]
  name = "github.com/OWASP/Amass"
  version = "2.9.2"

[[constraint]]
  name = "github.com/PuerkitoBio/fetchbot"
  version = "1.1.2"

[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "1.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/caffix/cloudflare-roundtripper"

[[constraint]]
  name = "github.com/cayleygraph/cayley"
  version = "0.7.5"

[[constraint]]
  branch = "master"
  name = "github.com/dghubble/go-twitter"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[constraint]]
  name = "github.com/go-ini/ini"
  version = "1.42.0"

[[constraint]]
  name = "github.com/google/uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/irfansharif/cfilter"
  version = "0.1.1"

[[constraint]]
  name = "github.com/johnnadratowski/golang-neo4j-bolt-driver"
  version = "0.1.0"

[[constraint]]
  name = "github.com/miekg/dns"
  version = "1.1.4"

[[constraint]]
  branch = "master"
  name = "github.com/qasaur/gremgo"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[prune]
  go-tests = true
  unused-packages = true
